### ISSUE TITLE
canal-for-ob 支持的ob版本有哪些，是否支持企业版 2.2.77

### ISSUE THREAD

**Issue by gentBai** [oceanbase/canal#28]
## Question
canal-for-ob 支持的ob版本有哪些，是否支持企业版 2.2.77

**Comment by whhe** [comment]
canal for ob 是直接跟 oblogproxy 对接的，所以支持版本主要看 oblogproxy。关于 oblogproxy 的支持情况，可以参考这里的 [OceanBase CDC 方案介绍](https://nightlies.apache.org/flink/flink-cdc-docs-release-3.1/zh/docs/connectors/flink-sources/oceanbase-cdc/#oceanbase-cdc-%e6%96%b9%e6%a1%88)
